package instrumentos;

public enum TipoInstrumento {
	GUITARRA, VIOLIN, VIOLA, PIANO, TROMPETA, CLARINETE, SAXOFON, BATERIA, BAJO, FLAUTA,
	TRIANGULO, ACORDEON, ARPA, MARACAS, PANDERETA, UKELELE, CHELO, FLAUTA_TRAVESERA, XILOFONO;
}
